BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"
BBFILE_COLLECTIONS += "je-example"
BBFILE_PATTERN_je-example = "^${LAYERDIR}/"
BBFILE_PRIORITY_je-example = "6"
LAYERSERIES_COMPAT_je-example = "scarthgap"
